## Colors configuration
[colors.primary]
background = '#191c0d'
foreground = '#e0e0df'

[colors.normal]
black = '#191c0d'
red = '#728179'
green = '#AA9153'
yellow = '#768788'
blue = '#989FA0'
magenta = '#B8BDBC'
cyan = '#B9C3C8'
white = '#e0e0df'

[colors.bright]
black = '#9c9c9c'
red = '#728179'
green = '#AA9153'
yellow = '#768788'
blue = '#989FA0'
magenta = '#B8BDBC'
cyan = '#B9C3C8'
white = '#e0e0df'
